'use client';

/**
 * HomepageCacheControl — admin card on /admin
 * ────────────────────────────────────────────
 * Shows the current state of the AI executive summary cache used by the
 * homepage Hero (cesru_homepage_cache row id='executive_summary') and lets
 * the admin force-regenerate it on demand. Useful after publishing a
 * notable result that the visitor should see before the natural 24h TTL.
 *
 * Force-regenerate calls GET /api/homepage/executive-summary?refresh=1 with
 * admin auth — the route gates ?refresh=1 behind authorizeAdminRequest().
 */

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { adminFetch } from '@/lib/admin-auth-client';

type CacheRow = {
  summary_th: string | null;
  source: string | null;
  model: string | null;
  generated_at: string | null;
  expires_at: string | null;
};

export default function HomepageCacheControl() {
  const [cache, setCache] = useState<CacheRow | null>(null);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);
  const [message, setMessage] = useState<{ kind: 'ok' | 'err'; text: string } | null>(null);

  const fetchCache = async () => {
    setLoading(true);
    const { data } = await supabase
      .from('cesru_homepage_cache')
      .select('summary_th, source, model, generated_at, expires_at')
      .eq('id', 'executive_summary')
      .maybeSingle();
    setCache(data || null);
    setLoading(false);
  };

  useEffect(() => {
    fetchCache();
  }, []);

  const expired =
    cache?.expires_at && new Date(cache.expires_at).getTime() < Date.now();

  const handleRegenerate = async () => {
    setRegenerating(true);
    setMessage(null);
    try {
      const res = await adminFetch('/api/homepage/executive-summary?refresh=1');
      const json = await res.json();
      if (!res.ok || json.error) {
        setMessage({ kind: 'err', text: json.error || `HTTP ${res.status}` });
      } else {
        setMessage({
          kind: 'ok',
          text: `สำเร็จ — สร้างสรุปใหม่จาก ${json.source} (${json.model}) เมื่อ ${new Date(
            json.generated_at,
          ).toLocaleString('th-TH')}`,
        });
        await fetchCache();
      }
    } catch (e: any) {
      setMessage({ kind: 'err', text: e.message || 'Network error' });
    } finally {
      setRegenerating(false);
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-md p-6">
      <div className="flex items-start justify-between gap-3 flex-wrap mb-4">
        <div>
          <h2 className="text-lg font-semibold text-gray-800 flex items-center gap-2">
            🤖 AI Executive Summary — หน้าแรก
          </h2>
          <p className="text-xs text-gray-500 mt-0.5 max-w-xl leading-relaxed">
            สรุป 3-5 ประโยคที่ AI สร้างจาก KPI + กิจกรรมล่าสุด แสดงบน Hero ของ /
            · cache อายุ 24 ชม. · กดปุ่มเพื่อสร้างใหม่ทันทีหลัง publish งานใหม่
          </p>
        </div>
        <button
          onClick={handleRegenerate}
          disabled={regenerating}
          className="px-4 py-2 bg-gradient-to-r from-emerald-600 to-teal-600 text-white rounded-lg text-sm font-medium hover:opacity-90 disabled:opacity-50 transition whitespace-nowrap"
        >
          {regenerating ? '⏳ กำลังสร้าง...' : '✨ สร้างสรุปใหม่'}
        </button>
      </div>

      {/* Status */}
      {loading ? (
        <div className="text-xs text-gray-400">กำลังโหลดสถานะ cache...</div>
      ) : !cache ? (
        <div className="bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 text-xs text-amber-800">
          ⚠ ยังไม่มี cache — กด "สร้างสรุปใหม่" เพื่อ generate ครั้งแรก
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
          <Field label="Status">
            <span
              className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full font-medium ${
                expired
                  ? 'bg-amber-100 text-amber-700'
                  : 'bg-emerald-100 text-emerald-700'
              }`}
            >
              <span
                className={`w-1.5 h-1.5 rounded-full ${
                  expired ? 'bg-amber-500' : 'bg-emerald-500 animate-pulse'
                }`}
              ></span>
              {expired ? 'หมดอายุ' : 'สดใหม่'}
            </span>
          </Field>
          <Field label="Generated by">
            <span className="text-gray-700">
              {cache.source || '—'}{' '}
              {cache.model && <span className="text-gray-400">· {cache.model}</span>}
            </span>
          </Field>
          <Field label="สร้างเมื่อ">
            <span className="text-gray-700">
              {cache.generated_at
                ? new Date(cache.generated_at).toLocaleString('th-TH', {
                    dateStyle: 'medium',
                    timeStyle: 'short',
                  })
                : '—'}
            </span>
          </Field>
          <Field label="หมดอายุเมื่อ">
            <span className="text-gray-700">
              {cache.expires_at
                ? new Date(cache.expires_at).toLocaleString('th-TH', {
                    dateStyle: 'medium',
                    timeStyle: 'short',
                  })
                : '—'}
            </span>
          </Field>
        </div>
      )}

      {/* Result */}
      {message && (
        <div
          className={`mt-3 rounded-lg px-3 py-2 text-xs ${
            message.kind === 'ok'
              ? 'bg-emerald-50 border border-emerald-200 text-emerald-700'
              : 'bg-red-50 border border-red-200 text-red-700'
          }`}
        >
          {message.kind === 'ok' ? '✓ ' : '✗ '}
          {message.text}
        </div>
      )}

      {/* Preview of current summary (truncated) */}
      {cache?.summary_th && (
        <details className="mt-3">
          <summary className="text-xs text-gray-500 cursor-pointer hover:text-gray-700">
            ▾ ดูเนื้อหา summary ปัจจุบัน
          </summary>
          <p className="mt-2 text-sm text-gray-700 leading-relaxed bg-gray-50 rounded-lg p-3 whitespace-pre-line">
            {cache.summary_th}
          </p>
        </details>
      )}
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="text-[10px] font-medium text-gray-400 uppercase tracking-wide">
        {label}
      </div>
      <div className="mt-0.5">{children}</div>
    </div>
  );
}
